services:
  valkyrie:
    build:
      context: ./valkyrie-sim
      args:
        ros_distro: ${ROS_DISTRO}
    image: develer/ros:${ROS_DISTRO}
    container_name: valkyrie
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}
      QT_X11_NO_MITSHM: 1
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
    volumes:
      - ${XSOCK}:${XSOCK}:rw
      - ${XAUTHORITY}:${XAUTHORITY}
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - /home/ste/src/ros2_ws/:/mnt/ws
    devices:
      - /dev/dri
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
             - driver: nvidia
               count: all
               capabilities: [gpu,graphics]
    command: ros2 launch -d valkyrie_bringup valkyrie_bringup_sim.launch.py launch_teleop:=false use_sim:=true rosbridge:=false websocket:=true

  backend:
    build: ./backend
    image: develer/backend
    container_name: backend
    network_mode: host
    stdin_open: true
    tty: true   

  frontend:
    build: ./frontend
    image: develer/frontend
    container_name: frontend
    network_mode: host
    stdin_open: true
    tty: true   
